version: '3.7'
services:
    api:
        build:
            context: ./
            dockerfile: Dockerfile
            target: base
        env_file:
            - .env.development
        environment:
            DB_HOST: postgres
            PORT: 8000
        volumes:
            - ./src:/usr/src/app/src
        ports:
            - '8000:8000'
        command: npm start
    postgres:
        build:
            context: ./db/
            dockerfile: Dockerfile.db
        env_file:
            - ./db/.env.development
    front:
        build:
            context: ./frontend/
            dockerfile: Dockerfile.front
            target: base
        environment:
            PORT: 3000
            REACT_APP_API_URL: http://localhost:8000
        volumes:
            - ./frontend/src:/usr/src/app/src
            - ./frontend/public:/usr/src/app/public
        ports:
            - '3000:3000'
        command: yarn start
